### PR TITLE
CLN grpc support

### PR DESCRIPTION
**Pull request by sekulicd**
Before this datadir was not setup correctly for CLN.
This also adds separate port for GRPC.

@tiero @altafan please review.

### CODE REVIEW

**Comment by tiero** [comment]
Can you please test the Readme commands as well? I assume before the folder was created in /root/.lighting ing

Just make sure the change is not breaking some other commands

**Comment by tiero** [comment]
Also can you double check that the latest permission PR https://github.com/vulpemventures/nigiri/pull/198 may have fixed your issues with datadir permission?

**Comment by sekulicd** [comment]
> Also can you double check that the latest permission PR #198 may have fixed your issues with datadir permission?

Still see permission err in logs
```
Core-Lightning starting
Couldn't watch /root/.lightning/bitcoin: Permission denied
Core-Lightning started, RPC available on port 9835
lightningd --network="${LIGHTNINGD_NETWORK}" "$@"
2024-12-23T09:51:02.506Z INFO    lightningd: v24.08.2
```

To reproduce build from master and run
`./build/nigiri-darwin-arm64 start —ln`

**Comment by tiero** [comment]
Ok I see how now having /root/.lightning being an issue ACK

**Review by tiero — APPROVED** [review]

**Pull request merged**
