### PR TITLE
expose bitcoin peer port to users

### PR DESCRIPTION
**Pull request by notmandatory**
To test my light wallet client I need to be able to connect it to my regtest node via the bitcoin peer port. This PR exposes the peer protocol port outside the docker-compose container on port 18432.

### CODE REVIEW

**Comment by notmandatory** [comment]
@altafan I added the changes you suggested, liquid came up and is exposing peer port as expected: 
```
$ docker ps
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS              PORTS                                                NAMES
c9bf27c5ebc9        vulpemventures/esplora:latest             "docker-entrypoint.s…"   18 seconds ago      Up 18 seconds       0.0.0.0:5001->5000/tcp                               resources_esplora-liquid_1
0771ce6bbb88        vulpemventures/esplora:latest             "docker-entrypoint.s…"   18 seconds ago      Up 18 seconds       0.0.0.0:5000->5000/tcp                               resources_esplora_1
41dc0605f36e        vulpemventures/nigiri-chopsticks:latest   "/app --use-faucet -…"   19 seconds ago      Up 18 seconds       0.0.0.0:3001->3000/tcp                               resources_chopsticks-liquid_1
4feaf2e28eb9        vulpemventures/nigiri-chopsticks:latest   "/app --use-faucet -…"   19 seconds ago      Up 19 seconds       0.0.0.0:3000->3000/tcp                               resources_chopsticks_1
983ff49e5f67        vulpemventures/electrs-liquid:latest      "/build/electrs -vvv…"   20 seconds ago      Up 19 seconds       0.0.0.0:60401->60401/tcp, 0.0.0.0:3012->3002/tcp     resources_electrs-liquid_1
939211d23fb1        vulpemventures/electrs:latest             "/build/electrs -vvv…"   20 seconds ago      Up 19 seconds       0.0.0.0:3002->3002/tcp, 0.0.0.0:51401->60401/tcp     resources_electrs_1
c53f08fa5d06        vulpemventures/liquid:latest              "elementsd -datadir=…"   20 seconds ago      Up 20 seconds       0.0.0.0:7041->18884/tcp, 0.0.0.0:7040->18886/tcp     resources_liquid_1
e70de026ae99        vulpemventures/bitcoin:latest             "bitcoind -datadir=/…"   20 seconds ago      Up 20 seconds       0.0.0.0:18432->19000/tcp, 0.0.0.0:18433->19001/tcp   resources_bitcoin_1
```

**Comment by notmandatory** [comment]
formatting fixed, thanks for the tip, I'm new to go lang. 

```
$ gofmt -l . 
cli/constants/constants.go
cli/controller/env.go
cli/controller/parser_test.go
$ gofmt -w .
$ gofmt -l .
$
```

**Comment by tiero** [comment]
> formatting fixed, thanks for the tip, I'm new to go lang.

You're welcome. I added the check in the CI pipeline so it's done automatically

**Comment by tiero** [comment]
Hey @notmandatory  the 0.0.8 release is out and contains your contribution.

With the latest pre-built binary everyone now could connect to the peer ports of bitcoin/elements. Thanks

**Pull request merged**
